import type { TemplateConfig } from "../apps/web/src/lib/pdf-template-types";
import {
  FAMILY_A_16COL,
  FAMILY_D_AL_MAKKAH,
  FAMILY_G_ZAVION,
  FAMILY_I_HASHMANI,
  FAMILY_J_AMT,
  FAMILY_J_AYAN,
  FAMILY_J_BUKHARI,
  FAMILY_J_CH_MEDICINE,
  FAMILY_J_GLOBAL,
  FAMILY_J_LIFE_CARE,
  FAMILY_J_ZAFAR,
  FAMILY_Z_EVERGREEN,
  FAMILY_Z_HAMZA,
} from "./pdf-format-presets";

export type JulyClosingDistributor = {
  code: string;
  name: string;
  region: "NORTH_1" | "NORTH_2" | "CENTER_1" | "CENTER_2" | "SOUTH";
  country: "PAK_1" | "PAK_2";
  city: string;
  formatCode: string;
  /** July Closing PDF filename(s) from analysis. */
  julyClosingPdfs: string[];
  templateConfig?: TemplateConfig | null;
};

/** All 46 July Closing PDFs mapped to 45 distributors (Al Rehman appears twice). */
export const JULY_CLOSING_DISTRIBUTORS: JulyClosingDistributor[] = [
  {
    code: "AIM-HYD",
    name: "AIM Pharma HYD",
    region: "SOUTH",
    country: "PAK_1",
    city: "Hyderabad",
    formatCode: "fmt-a-ssr-stock-return",
    julyClosingPdfs: ["AIM Pharma HYD.pdf"],
  },
  {
    code: "LAL-SIBBI",
    name: "Lal Drug Agency Sibbi",
    region: "SOUTH",
    country: "PAK_1",
    city: "Sibbi",
    formatCode: "fmt-a-ssr-stock-return",
    julyClosingPdfs: ["Lal Drug Agency Sibbi.pdf"],
  },
  {
    code: "RELIABLE-MPK",
    name: "Reliable Pharma MPK",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Mirpur Khas",
    formatCode: "fmt-a-ssr-stock-return",
    julyClosingPdfs: ["Reliable Pharma MPK.pdf"],
  },
  {
    code: "AL-HARAM-KOHAT",
    name: "Al Haram Enterprises Kohat",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Kohat",
    formatCode: "fmt-a-ssr-stock-return",
    julyClosingPdfs: ["Al Haram Enterprises Kohat.pdf"],
    templateConfig: FAMILY_A_16COL,
  },
  {
    code: "AL-SHIFA-JAMPUR",
    name: "AL Shifa Enterprises Jampur",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Jampur",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["AL Shifa Enterprises Jampur.pdf"],
  },
  {
    code: "AQ-SARGODHA",
    name: "AQ Enterprises Sargodha",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Sargodha",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["AQ Enterprises Sargodha.pdf"],
  },
  {
    code: "AL-HARMAIN-DGK",
    name: "Al Harmain Enterprises DG Khan",
    region: "CENTER_1",
    country: "PAK_1",
    city: "DG Khan",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["Al Harmain ENterprises DG Khan.pdf"],
  },
  {
    code: "NG-SWL",
    name: "N&G Enterprises SWL",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Sahiwal",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["N&G Enterprises SWL.pdf"],
  },
  {
    code: "WELLCOME-ALIPUR",
    name: "Wellcome Pharma Ali Pur",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Ali Pur",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["Wellcome Pharma alipur.pdf"],
  },
  {
    code: "SHAHZAIB-OKARA",
    name: "Shahzaib Pharma Okara",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Okara",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["sHAHZAIB pHARMA Okara30.pdf"],
  },
  {
    code: "RUMAN-PROMO-RYK",
    name: "Ruman Medicine Promotion RYK",
    region: "SOUTH",
    country: "PAK_1",
    city: "Rahim Yar Khan",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["Ruman Medicine Promotion RYK.pdf"],
  },
  {
    code: "RUMAN-TRADE-RYK",
    name: "Ruman Medicine Trade RYK",
    region: "SOUTH",
    country: "PAK_1",
    city: "Rahim Yar Khan",
    formatCode: "fmt-b-medicronis-erp",
    julyClosingPdfs: ["Ruman Medicine Trade RYK.pdf"],
  },
  {
    code: "EVERGREEN-DIK",
    name: "Evergreen Enterprises DI Khan",
    region: "NORTH_1",
    country: "PAK_1",
    city: "DI Khan",
    formatCode: "fmt-e-trad-rate-net-sale",
    julyClosingPdfs: ["Evergreen Enterprises DI Khan.pdf"],
    templateConfig: FAMILY_Z_EVERGREEN,
  },
  {
    code: "AL-REHMAN-LHR",
    name: "Al Rehman Medical Sources Lahore",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Lahore",
    formatCode: "fmt-c-item-desc-net-sales",
    julyClosingPdfs: [
      "Al Rehman  Medical Sources Lahore.pdf",
      "Al Rehman Medical Sources Lahore.pdf",
    ],
  },
  {
    code: "BASHIR-GUJ",
    name: "Bashir Pharma Gujranwala",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Gujranwala",
    formatCode: "fmt-c-item-desc-net-sales",
    julyClosingPdfs: ["Bashir Pharma Gujranwala.pdf"],
  },
  {
    code: "MC-RWP",
    name: "M&C RWP",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Rawalpindi",
    formatCode: "fmt-c-item-desc-net-sales",
    julyClosingPdfs: ["M&C RWP.pdf"],
  },
  {
    code: "PHARMARITE-JEH",
    name: "Pharmarite Distributor Jehlum",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Jhelum",
    formatCode: "fmt-c-item-desc-net-sales",
    julyClosingPdfs: ["Pharmarite Distributor Jehlum.pdf"],
  },
  {
    code: "SHAFIQ-KHANPUR",
    name: "Shafiq Medicine Company Khanpur",
    region: "SOUTH",
    country: "PAK_1",
    city: "Khanpur",
    formatCode: "fmt-c-item-desc-net-sales",
    julyClosingPdfs: ["Shafiq Medicine Company Khanpur.pdf"],
  },
  {
    code: "HAJI-NIZAM-QTA",
    name: "Haji Nizam & Sons Quetta",
    region: "SOUTH",
    country: "PAK_1",
    city: "Quetta",
    formatCode: "fmt-c-item-desc-net-sales",
    julyClosingPdfs: ["Haji Nizam & Sons Quetta.pdf"],
  },
  {
    code: "FAIZ-RAJANPUR",
    name: "Faiz Enterprises Rajanpur",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Rajanpur",
    formatCode: "fmt-f-simple-sales",
    julyClosingPdfs: ["Faiz Enterprises Rajanpur.pdf"],
  },
  {
    code: "AL-MAKKAH-BUNER",
    name: "Al Makkah Trading Buner",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Buner",
    formatCode: "fmt-d-product-name-tp-tax",
    julyClosingPdfs: ["Al Makkah Trading Buner.PDF"],
    templateConfig: FAMILY_D_AL_MAKKAH,
  },
  {
    code: "KAMAL-TIMERGARAH",
    name: "Kamal Medicine Company Timergarah",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Timergarah",
    formatCode: "fmt-d-product-name-tp-tax",
    julyClosingPdfs: ["Kamal Medicine Company Timergarah.PDF"],
  },
  {
    code: "MEDICAMP-PSW",
    name: "Medicamp PSW",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Peshawar",
    formatCode: "fmt-d-product-name-tp-tax",
    julyClosingPdfs: ["Medicamp PSW.PDF"],
  },
  {
    code: "UMAR-SWABI",
    name: "Umar Medicine Swabi",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Swabi",
    formatCode: "fmt-d-product-name-tp-tax",
    julyClosingPdfs: ["Umar Medicine Swabi.PDF"],
  },
  {
    code: "HAMED-BANNU-PROMO",
    name: "Hamed Pharma Bannu (Promotion)",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Bannu",
    formatCode: "fmt-e-trad-rate-net-sale",
    julyClosingPdfs: ["Hamed Pharma Bannu Promotion.pdf"],
  },
  {
    code: "HAMED-BANNU-TRADE",
    name: "Hamed Pharma Bannu (Trade)",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Bannu",
    formatCode: "fmt-e-trad-rate-net-sale",
    julyClosingPdfs: ["Hamed Pharma Bannu Trade.pdf"],
  },
  {
    code: "MEHRAN-MARDAN",
    name: "Mehran Traders Mardan",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Mardan",
    formatCode: "fmt-e-trad-rate-net-sale",
    julyClosingPdfs: ["Mehran Traders Mardan.pdf"],
  },
  {
    code: "PUNJAB-LAYYAH",
    name: "Punjab Medicine Layyah",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Layyah",
    formatCode: "fmt-f-simple-sales",
    julyClosingPdfs: ["Punjab Medicine Layyah 22.pdf"],
  },
  {
    code: "CHISHTI-MULTAN",
    name: "Chishti Pharma Multan",
    region: "SOUTH",
    country: "PAK_1",
    city: "Multan",
    formatCode: "fmt-g-code-product-net-sale",
    julyClosingPdfs: ["Chishti Pharma Multan.pdf"],
  },
  {
    code: "ZAVION-JHANG",
    name: "Zavion Pharma Jhang",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Jhang",
    formatCode: "fmt-g-code-product-net-sale",
    julyClosingPdfs: ["Zavion Pharma Jhang.pdf"],
    templateConfig: FAMILY_G_ZAVION,
  },
  {
    code: "MASHAL-BAJAUR",
    name: "Mashal Enterprises Bajaur",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Bajaur",
    formatCode: "fmt-h-name-price-sales",
    julyClosingPdfs: ["Mashal Enterprises Bajaur.pdf"],
  },
  {
    code: "HASHMANI-KHI",
    name: "Hashmani Health Care Karachi",
    region: "SOUTH",
    country: "PAK_1",
    city: "Karachi",
    formatCode: "fmt-i-vertical-qty-bon",
    julyClosingPdfs: ["Hashmani Health Care Karachi.pdf"],
    templateConfig: FAMILY_I_HASHMANI,
  },
  {
    code: "AYAN-TAUNSA",
    name: "Ayan Pharma Taunsa",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Taunsa",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Ayan Pharma Taunsa.pdf"],
    templateConfig: FAMILY_J_AYAN,
  },
  {
    code: "CH-MED-MWL",
    name: "Ch Medicine MWL",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Mianwali",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Ch Medicine MWL.pdf"],
    templateConfig: FAMILY_J_CH_MEDICINE,
  },
  {
    code: "GLOBAL-SKP",
    name: "Globar Enterprises SKP",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Sheikhupura",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Globar Enterprises SKP.PDF"],
    templateConfig: FAMILY_J_GLOBAL,
  },
  {
    code: "MRWA-BWP",
    name: "Mrwa Enterprises BWP",
    region: "SOUTH",
    country: "PAK_1",
    city: "Bahawalpur",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Mrwa Enterprises BWP.pdf"],
  },
  {
    code: "NOOR-KHAN-MINGORA",
    name: "Noor Khan Mingora",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Mingora",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Noor Khan Mingora.pdf", "Noor KHan minogra promotion30.pdf"],
  },
  {
    code: "ZAFAR-NWS",
    name: "Zafar & Sons NWS",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Nowshera",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Zafar & Sons NWS.pdf"],
    templateConfig: FAMILY_J_ZAFAR,
  },
  {
    code: "TAWAKAL-ABBT",
    name: "New Tawakal Enterprises ABBT",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Abbottabad",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["New Tawakal Enterprises ABBT.pdf"],
  },
  {
    code: "BUKHARI-MBD",
    name: "Bukhari Traders MBD",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Mardan",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Bukhari Traders MBD.pdf"],
    templateConfig: FAMILY_J_BUKHARI,
  },
  {
    code: "AMT-FSD",
    name: "AMT FSD",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Faisalabad",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["AMT FSD.pdf"],
    templateConfig: FAMILY_J_AMT,
  },
  {
    code: "HAMZA-TTS",
    name: "Hamza Medicine TTS",
    region: "NORTH_1",
    country: "PAK_1",
    city: "Tatral",
    formatCode: "fmt-f-simple-sales",
    julyClosingPdfs: ["Hamza Medicine TTS.pdf"],
    templateConfig: FAMILY_Z_HAMZA,
  },
  {
    code: "LIFE-CARE-GUJRAT",
    name: "Life Care Distributor Gujrat",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Gujrat",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["Life Care Distributor Gujrat.pdf"],
    templateConfig: FAMILY_J_LIFE_CARE,
  },
  {
    code: "HAMZA-TRADERS-KASUR",
    name: "The Hamza Traders Kasur",
    region: "CENTER_1",
    country: "PAK_1",
    city: "Kasur",
    formatCode: "fmt-j-no-table",
    julyClosingPdfs: ["The Hamza Traders Kasur.pdf"],
  },
];

/** Flat list of all 46 July Closing PDF filenames with assigned format code. */
export const JULY_CLOSING_PDF_ASSIGNMENTS = JULY_CLOSING_DISTRIBUTORS.flatMap((d) =>
  d.julyClosingPdfs.map((pdf) => ({ pdf, formatCode: d.formatCode, distributorCode: d.code })),
);
