/* Auto-generated by scripts/generate-seed-data.py — do not edit by hand */
export const SEED_GEO = {
  "managers": [
    "ASM Vacant",
    "Al Khaliq Enterprises / Malik & Sons",
    "Ali Ahmed",
    "Amir Khan",
    "Asad Mahmood",
    "Asghar Ali",
    "Atif Saeed",
    "Barkat Ullah",
    "Buner",
    "Chitral",
    "Direct Party",
    "Direct Party + Badin",
    "Direct Sales",
    "Faisal Gulzar",
    "HOS FSD + SWL",
    "HOS WT + RWP",
    "Hammad Ali Anjum",
    "Hammad Basharat",
    "Hari Pur",
    "Imran Ahmed",
    "Imran Rasheed",
    "Iqbal Hussain",
    "Karachi",
    "Khalil Nawaz",
    "Loralai",
    "M Adnan",
    "M Ali",
    "M Asghar",
    "M Asim",
    "M Hassan",
    "M Imran",
    "M Irfan",
    "M Kashif",
    "M Riaz",
    "M Sohail",
    "M Tayyab",
    "M Tufail",
    "Manzoor Hussain",
    "Mir Pur Khas",
    "Mudassar Gill",
    "Muhammad Nawaz",
    "Nadeem Jaffer",
    "Nagina Buzdar",
    "Nasir Abbas",
    "Nasir Khan",
    "Nasir Pervaiz",
    "Noor Muhammad",
    "PAK1",
    "PAK2",
    "Rehan Hussain",
    "Riasat Ali",
    "Rizwan Sohail",
    "Rooh Ul Amin",
    "Sakhawat Pasha",
    "Sami Ul Haq",
    "Sami Ullah",
    "Saqib Ali",
    "Shafique Ahmed Bajwa",
    "Shahzad Ahmed",
    "Sher Ali",
    "Shoaib Ur Rehman",
    "Sibbi",
    "Sudais Khan",
    "Syed Mehtab Ali",
    "Syed Wajih Bukhari",
    "Vacant",
    "Waqas Ahmed",
    "Waseem Siddiqui",
    "Yousaf Bhatti",
    "ZA Traders",
    "Zulfiqar Ali"
  ],
  "territories": [
    {
      "name": "Abbotabad",
      "manager": "M Tufail"
    },
    {
      "name": "Ali Pur",
      "manager": "Nasir Abbas"
    },
    {
      "name": "Bajaur",
      "manager": "Nasir Khan"
    },
    {
      "name": "Bannu",
      "manager": "Sami Ul Haq"
    },
    {
      "name": "Batkhela",
      "manager": "Vacant"
    },
    {
      "name": "Bloach",
      "manager": "Noor Muhammad"
    },
    {
      "name": "Buner",
      "manager": "Vacant"
    },
    {
      "name": "Bwp",
      "manager": "Vacant"
    },
    {
      "name": "Center-1",
      "manager": "M Asghar"
    },
    {
      "name": "Center-2",
      "manager": "Mudassar Gill"
    },
    {
      "name": "Charsadda",
      "manager": "Vacant"
    },
    {
      "name": "DG Khan",
      "manager": "M Ali"
    },
    {
      "name": "DGK",
      "manager": "Waqas Ahmed"
    },
    {
      "name": "DIK",
      "manager": "Nadeem Jaffer"
    },
    {
      "name": "Direct",
      "manager": "Direct Sales"
    },
    {
      "name": "FSD + SWL",
      "manager": "HOS FSD + SWL"
    },
    {
      "name": "Faisalabad",
      "manager": "Vacant"
    },
    {
      "name": "Fsd-1",
      "manager": "Vacant"
    },
    {
      "name": "Fsd-2",
      "manager": "Vacant"
    },
    {
      "name": "GWL",
      "manager": "M Hassan"
    },
    {
      "name": "Gujranwala",
      "manager": "Shafique Ahmed Bajwa"
    },
    {
      "name": "Gujrat",
      "manager": "Manzoor Hussain"
    },
    {
      "name": "HYD-1",
      "manager": "Amir Khan"
    },
    {
      "name": "HYD-2",
      "manager": "Vacant"
    },
    {
      "name": "Hari Pur",
      "manager": "Hari Pur"
    },
    {
      "name": "Hyd",
      "manager": "Vacant"
    },
    {
      "name": "Hyderabad",
      "manager": "M Adnan"
    },
    {
      "name": "ISB",
      "manager": "Vacant"
    },
    {
      "name": "Jam Pur",
      "manager": "Yousaf Bhatti"
    },
    {
      "name": "Jhang",
      "manager": "Direct Party"
    },
    {
      "name": "Jhelum",
      "manager": "M Asim"
    },
    {
      "name": "KHI",
      "manager": "Karachi"
    },
    {
      "name": "Kasur",
      "manager": "Vacant"
    },
    {
      "name": "Khan Pur",
      "manager": "M Tayyab"
    },
    {
      "name": "Khanewal",
      "manager": "Direct Party"
    },
    {
      "name": "Kohat",
      "manager": "Vacant"
    },
    {
      "name": "Lahore",
      "manager": "Vacant"
    },
    {
      "name": "Layyah",
      "manager": "Vacant"
    },
    {
      "name": "Lhr-4",
      "manager": "Vacant"
    },
    {
      "name": "MP Khas",
      "manager": "Riasat Ali"
    },
    {
      "name": "MPK",
      "manager": "Mir Pur Khas"
    },
    {
      "name": "Mandi",
      "manager": "Syed Wajih Bukhari"
    },
    {
      "name": "Mardan",
      "manager": "Amir Khan"
    },
    {
      "name": "Mianwali",
      "manager": "Faisal Gulzar"
    },
    {
      "name": "Mingora-1",
      "manager": "Iqbal Hussain"
    },
    {
      "name": "Multan",
      "manager": "Rehan Hussain"
    },
    {
      "name": "Mux + RYK",
      "manager": "Rehan Hussain"
    },
    {
      "name": "Mux-1",
      "manager": "Vacant"
    },
    {
      "name": "Mux-2",
      "manager": "Imran Ahmed"
    },
    {
      "name": "N. Shah",
      "manager": "Zulfiqar Ali"
    },
    {
      "name": "National",
      "manager": "Shahzad Ahmed"
    },
    {
      "name": "North",
      "manager": "Syed Mehtab Ali"
    },
    {
      "name": "Okara",
      "manager": "M Kashif"
    },
    {
      "name": "PAK1",
      "manager": "PAK1"
    },
    {
      "name": "PAK2",
      "manager": "PAK2"
    },
    {
      "name": "PWR + BANU",
      "manager": "Syed Mehtab Ali"
    },
    {
      "name": "PWR-1",
      "manager": "Vacant"
    },
    {
      "name": "PWR-2",
      "manager": "Vacant"
    },
    {
      "name": "Pak-1",
      "manager": "Asghar Ali"
    },
    {
      "name": "Pashtoon",
      "manager": "M Riaz"
    },
    {
      "name": "Pir Mahal",
      "manager": "Al Khaliq Enterprises / Malik & Sons"
    },
    {
      "name": "QTA",
      "manager": "Vacant"
    },
    {
      "name": "Quetta",
      "manager": "ASM Vacant"
    },
    {
      "name": "RWP 3",
      "manager": "Vacant"
    },
    {
      "name": "RWP-1",
      "manager": "Vacant"
    },
    {
      "name": "RWP-2",
      "manager": "Vacant"
    },
    {
      "name": "RYK",
      "manager": "M Imran"
    },
    {
      "name": "Rajan Pur",
      "manager": "Sami Ullah"
    },
    {
      "name": "Rawalpindi",
      "manager": "Vacant"
    },
    {
      "name": "SGD",
      "manager": "M Irfan"
    },
    {
      "name": "SKP",
      "manager": "Asad Mahmood"
    },
    {
      "name": "SWL",
      "manager": "Muhammad Nawaz"
    },
    {
      "name": "SWT + RWP",
      "manager": "HOS WT + RWP"
    },
    {
      "name": "SZH",
      "manager": "Vacant"
    },
    {
      "name": "Shadad Pur",
      "manager": "Direct Party + Badin"
    },
    {
      "name": "Shahdra",
      "manager": "Waseem Siddiqui"
    },
    {
      "name": "Shalamar",
      "manager": "Vacant"
    },
    {
      "name": "Sialkot",
      "manager": "Vacant"
    },
    {
      "name": "South",
      "manager": "Nasir Pervaiz"
    },
    {
      "name": "Swabi",
      "manager": "Vacant"
    },
    {
      "name": "Swat",
      "manager": "Rooh Ul Amin"
    },
    {
      "name": "Swat-1",
      "manager": "M Sohail"
    },
    {
      "name": "Taunsa",
      "manager": "Nagina Buzdar"
    },
    {
      "name": "Temergera",
      "manager": "Sudais Khan"
    },
    {
      "name": "Toba",
      "manager": "Rizwan Sohail"
    },
    {
      "name": "WS",
      "manager": "Chitral"
    },
    {
      "name": "Waana",
      "manager": "Saqib Ali"
    }
  ],
  "areas": [
    {
      "name": "Bannu",
      "manager": "Vacant"
    },
    {
      "name": "Center-1",
      "manager": "M Asghar"
    },
    {
      "name": "Center-2",
      "manager": "Mudassar Gill"
    },
    {
      "name": "Centre",
      "manager": "Asghar Ali"
    },
    {
      "name": "Centre-1",
      "manager": "Vacant"
    },
    {
      "name": "DG Khan",
      "manager": "Hammad Ali Anjum"
    },
    {
      "name": "FSD + SWL",
      "manager": "HOS FSD + SWL"
    },
    {
      "name": "Faisalabad",
      "manager": "Vacant"
    },
    {
      "name": "Gujranwala",
      "manager": "Shafique Ahmed Bajwa"
    },
    {
      "name": "Hyderabad",
      "manager": "M Adnan"
    },
    {
      "name": "Karachi",
      "manager": "Karachi"
    },
    {
      "name": "Lahore",
      "manager": "Atif Saeed"
    },
    {
      "name": "Multan",
      "manager": "Rehan Hussain"
    },
    {
      "name": "Mux + RYK",
      "manager": "Rehan Hussain"
    },
    {
      "name": "National",
      "manager": "Shahzad Ahmed"
    },
    {
      "name": "North",
      "manager": "Vacant"
    },
    {
      "name": "PAK1",
      "manager": "PAK1"
    },
    {
      "name": "PAK2",
      "manager": "PAK2"
    },
    {
      "name": "PWR + BANU",
      "manager": "Syed Mehtab Ali"
    },
    {
      "name": "Pak-1",
      "manager": "Asghar Ali"
    },
    {
      "name": "Peshawar",
      "manager": "Vacant"
    },
    {
      "name": "Quetta",
      "manager": "ASM Vacant"
    },
    {
      "name": "Rahim Yar Khan",
      "manager": "M Imran"
    },
    {
      "name": "Rawalpindi",
      "manager": "Vacant"
    },
    {
      "name": "SWT + RWP",
      "manager": "HOS WT + RWP"
    },
    {
      "name": "South",
      "manager": "Nasir Pervaiz"
    },
    {
      "name": "Swat",
      "manager": "Rooh Ul Amin"
    }
  ],
  "regions": [
    {
      "name": "Center-1",
      "manager": "Vacant"
    },
    {
      "name": "Center-2",
      "manager": "Mudassar Gill"
    },
    {
      "name": "Centre",
      "manager": "Asghar Ali"
    },
    {
      "name": "Centre-1",
      "manager": "M Asghar"
    },
    {
      "name": "DG Khan",
      "manager": "Hammad Ali Anjum"
    },
    {
      "name": "DI Khan",
      "manager": "Vacant"
    },
    {
      "name": "FSD + SWL",
      "manager": "HOS FSD + SWL"
    },
    {
      "name": "Faisalabad",
      "manager": "Sakhawat Pasha"
    },
    {
      "name": "Hyderabad",
      "manager": "M Adnan"
    },
    {
      "name": "Lahore",
      "manager": "Atif Saeed"
    },
    {
      "name": "Multan",
      "manager": "Rehan Hussain"
    },
    {
      "name": "National",
      "manager": "Shahzad Ahmed"
    },
    {
      "name": "North",
      "manager": "Syed Mehtab Ali"
    },
    {
      "name": "PAK1",
      "manager": "PAK1"
    },
    {
      "name": "PAK2",
      "manager": "PAK2"
    },
    {
      "name": "PWR + Bannu",
      "manager": "Syed Mehtab Ali"
    },
    {
      "name": "Pak-1",
      "manager": "Asghar Ali"
    },
    {
      "name": "Peshawar",
      "manager": "Vacant"
    },
    {
      "name": "Quetta",
      "manager": "Vacant"
    },
    {
      "name": "Rahim Yar Khan",
      "manager": "M Imran"
    },
    {
      "name": "SWT + RWP",
      "manager": "HOS WT + RWP"
    },
    {
      "name": "South",
      "manager": "Nasir Pervaiz"
    },
    {
      "name": "Swat",
      "manager": "M Sohail"
    }
  ],
  "zones": [
    {
      "name": "Center-1",
      "manager": "HOS FSD + SWL"
    },
    {
      "name": "Center-2",
      "manager": "Mudassar Gill"
    },
    {
      "name": "Centre",
      "manager": "Asghar Ali"
    },
    {
      "name": "Centre-1",
      "manager": "Vacant"
    },
    {
      "name": "Centre-2",
      "manager": "Vacant"
    },
    {
      "name": "National",
      "manager": "Shahzad Ahmed"
    },
    {
      "name": "North",
      "manager": "Syed Mehtab Ali"
    },
    {
      "name": "PAK1",
      "manager": "PAK1"
    },
    {
      "name": "PAK2",
      "manager": "PAK2"
    },
    {
      "name": "Pak-1",
      "manager": "Asghar Ali"
    },
    {
      "name": "South",
      "manager": "Nasir Pervaiz"
    }
  ]
} as const;
