"""
Generate prisma/data/*.ts seed modules from client Excel workbooks.
Run: python scripts/generate-seed-data.py
"""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from datetime import datetime
from difflib import SequenceMatcher
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "prisma" / "data"
OUT.mkdir(parents=True, exist_ok=True)

PRODUCT_XLSX = Path(r"d:\Downloads\final_product_list (1).xlsx")
TRANSFORMER_XLSX = Path(r"d:\Downloads\Transformer TGTs -2026.xlsx")
TRADE_XLSX = Path(r"d:\Downloads\Trade Targets - 2026.xlsx")

# Chat history: ProductGroup is Medicronis | Transformer; product sheet uses "Trade" for Medicronis.
GROUP_MAP = {
    "trade": "Medicronis",
    "medicronis": "Medicronis",
    "transformer": "Transformer",
}


def ts_escape(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def write_ts_const(path: Path, export_name: str, value) -> None:
    body = json.dumps(value, indent=2, ensure_ascii=False)
    # Prefer TypeScript `as const` for type narrowing where useful
    path.write_text(
        f"/* Auto-generated by scripts/generate-seed-data.py — do not edit by hand */\n"
        f"export const {export_name} = {body} as const;\n",
        encoding="utf-8",
    )
    print(f"wrote {path.relative_to(ROOT)} ({len(value) if hasattr(value, '__len__') else 'obj'})")


def load_products():
    import openpyxl

    wb = openpyxl.load_workbook(PRODUCT_XLSX, data_only=True)
    ws = wb["Products"]
    products = []
    for r in ws.iter_rows(min_row=2, values_only=True):
        if not r or not r[0]:
            continue
        sku = str(r[0]).strip()
        name = str(r[1]).strip() if r[1] else ""
        category = str(r[2]).strip() if r[2] else None
        group_raw = str(r[4]).strip() if r[4] else "Trade"
        group = GROUP_MAP.get(group_raw.lower(), group_raw)
        composition = str(r[5]).strip() if r[5] else None
        manufacturer = str(r[6]).strip() if r[6] else None
        shipper = int(r[7]) if r[7] is not None and str(r[7]).strip() != "" else None
        def num(v):
            if v is None or v == "":
                return None
            try:
                return float(v)
            except Exception:
                return None

        aliases_raw = str(r[16]).strip() if len(r) > 16 and r[16] else ""
        aliases = [a.strip() for a in aliases_raw.split(",") if a.strip()] if aliases_raw else []
        # Sheet "aliases" often repeat composition/manufacturer — still seed as provided
        products.append(
            {
                "sku": sku,
                "name": name,
                "category": category,
                "group": group,
                "composition": composition,
                "manufacturer": manufacturer,
                "shipperSize": shipper,
                "mrp": num(r[8]),
                "tp": num(r[9]),
                "oldSp": num(r[10]),
                "newSp": num(r[11]),
                "netPrice": num(r[12]),
                "tax": num(r[13]),
                "netPriceWith1Pct": num(r[14]),
                "bonus": str(r[15]).strip() if r[15] else None,
                "aliases": aliases,
            }
        )
    wb.close()
    return products


def norm_key(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())


def build_product_matcher(products):
    by_exact = {p["name"]: p["sku"] for p in products}
    by_norm = {norm_key(p["name"]): p["sku"] for p in products}
    # also index aliases
    for p in products:
        for a in p["aliases"]:
            by_exact.setdefault(a, p["sku"])
            by_norm.setdefault(norm_key(a), p["sku"])
    return by_exact, by_norm, products


def resolve_product_sku(name: str, by_exact, by_norm, products) -> str | None:
    if name in by_exact:
        return by_exact[name]
    nk = norm_key(name)
    if nk in by_norm:
        return by_norm[nk]
    # slash alternatives: "Apivo / Medegar 120ml"
    for part in re.split(r"[/|]", name):
        part = part.strip()
        if not part:
            continue
        if part in by_exact:
            return by_exact[part]
        pn = norm_key(part)
        if pn in by_norm:
            return by_norm[pn]
    # fuzzy on product names
    best = None
    best_score = 0.0
    for p in products:
        score = SequenceMatcher(None, nk, norm_key(p["name"])).ratio()
        if score > best_score:
            best_score = score
            best = p["sku"]
    if best_score >= 0.82:
        return best
    # common renames / typos from target sheets
    MANUAL = {
        "peergo gel 30gm": None,  # filled below via norm of PeerGo Gel 30g
        "novagen 1g": None,
        "novagen 1g inj": None,
        "ectafin 1g inj": None,
        "ectafin 2g inj": None,
        "g.tax 1g": None,
        "gtn cream 30g": None,
        "khaajgo bar 85g": None,
        "clan plus syp 120ml": None,
        "clan plus tab": None,
        "colimax drops": None,
        "maxy 400mg/250ml": None,
        "trenmed tab 20's": None,
        "zil 20mg cap": None,
        "zil 40mg cap": None,
        "apivo / medegar 120ml": None,
        "hostenil / kufxy syp": None,
        "lancix inj. 10's": None,
        "lancix inj. 25's": None,
        "mediscon liquid 120ml": None,
        "medivit syp 120ml": None,
        "nida 500mg/100ml": None,
        "noson balm 20gm": None,
        "paxcal syp 120ml": None,
        "paxcal tab 20's": None,
        "salberry / berryflow sachet": None,
        "steps inn cream": None,
        "v-fol tab": None,
    }
    # Build manual map from fuzzy against known names once we print misses
    return None


def parse_target_sheet(path: Path, sheet: str):
    import openpyxl

    # read_only + max_col avoids MemoryError on large Trade workbook
    wb = openpyxl.load_workbook(path, data_only=True, read_only=True)
    ws = wb[sheet]
    hdr_i = None
    hdr = None
    month_cols: list[tuple[int, int, int]] = []
    out = []

    for i, r in enumerate(ws.iter_rows(min_col=1, max_col=20, values_only=True)):
        if hdr_i is None:
            if r and len(r) > 9 and r[3] == "Name" and r[5] == "Territory":
                hdr_i = i
                hdr = r
                for ci, v in enumerate(hdr):
                    if isinstance(v, datetime):
                        month_cols.append((ci, v.year, v.month))
            continue

        if not r or not r[5] or not r[9]:
            continue
        product = str(r[9]).strip()
        if product.upper() in ("TOTAL UNITS", "TOTAL VALUE", "PRODUCT NAME"):
            continue
        manager = str(r[3]).strip() if r[3] else "Vacant"
        if not manager:
            manager = "Vacant"
        desig = str(r[4]).strip() if r[4] else None
        terr = str(r[5]).strip()
        area = str(r[6]).strip() if r[6] else None
        region = str(r[7]).strip() if r[7] else None
        zone = str(r[8]).strip() if r[8] else None
        if not terr or not area or not region or not zone or not product:
            continue
        months = []
        for ci, y, m in month_cols:
            q = r[ci] if ci < len(r) else None
            if q is None or q == "":
                continue
            try:
                qf = float(q)
            except Exception:
                continue
            if qf < 0:
                continue
            months.append({"year": y, "month": m, "quantity": qf})
        out.append(
            {
                "manager": manager,
                "designation": desig,
                "territory": terr,
                "area": area,
                "region": region,
                "zone": zone,
                "productName": product,
                "months": months,
            }
        )

    wb.close()
    if hdr_i is None:
        raise RuntimeError(f"Header not found in {path.name}/{sheet}")
    return out


def improve_matcher_with_manual(products, by_exact, by_norm):
    """Hand map common target-sheet names → product SKU after inspecting both lists."""
    name_to_sku = {p["name"]: p["sku"] for p in products}
    # Heuristic: find best product for known miss patterns by keyword
    keywords = [
        ("peergo", "PeerGo"),
        ("peer go", "PeerGo"),
        ("novagen", "Novagen"),
        ("ectafin", "Ectafin"),
        ("g tax", "G.Tax"),
        ("g.tax", "G.Tax"),
        ("gtn", "GTN"),
        ("khaajgo bar", "KhaajGo"),
        ("khaajgo soap", "KhaajGo Soap"),
        ("clan plus syp", "Clan"),
        ("clan plus tab", "Clan"),
        ("colimax", "Coli"),
        ("maxy", "Maxy"),
        ("trenmed", "Tren"),
        ("zil 20", "Zil"),
        ("zil 40", "Zil"),
        ("apivo", "Apivo"),
        ("medegar", "Medegar"),
        ("hostenil", "Hoste"),
        ("kufxy", "Kuf"),
        ("lancix", "Lancix"),
        ("mediscon", "Mediscon"),
        ("medivit", "Medivit"),
        ("nida", "Nida"),
        ("noson", "Nos"),
        ("paxcal", "Paxcal"),
        ("salberry", "Sal"),
        ("berryflow", "Berry"),
        ("steps inn", "Steps"),
        ("v-fol", "V-Fol"),
        ("vfol", "V-Fol"),
    ]
    # We'll resolve misses at runtime with SequenceMatcher + slash split only;
    # add explicit overrides once we know product names.
    overrides = {}
    for p in products:
        n = p["name"].lower()
        sku = p["sku"]
        overrides[norm_key(p["name"])] = sku
        # strip packing noise variants
        overrides[norm_key(re.sub(r"\b(ml|mg|g|gm|tab|syp|cap|inj|cream|gel|drops?|sachet|liquid|bar)\b", "", n))] = sku
    return overrides


def main():
    products = load_products()
    by_exact, by_norm, _ = build_product_matcher(products)
    # print product names for override building
    print("=== Products ===")
    for p in products:
        print(f"  {p['sku']}: {p['name']} [{p['group']}]")

    transformer = parse_target_sheet(TRANSFORMER_XLSX, "Transformer")
    trade = parse_target_sheet(TRADE_XLSX, "Trade Rev. TGTs -2026")
    all_rows = transformer + trade
    print(f"\nTransformer rows: {len(transformer)}, Trade rows: {len(trade)}")

    # Explicit target-sheet product names → SKU (after inspecting master list)
    EXPLICIT_OVERRIDES: dict[str, str] = {
        "Peer Go Gel 30gm": "MED-0003",
        "Steps Inn Cream": "MED-0004",
        "GTN Cream 30G": "MED-0005",
        "NosOn Balm 20gm": "MED-0006",
        "Apivo / Medegar 120ml": "MED-0007",
        "HosteNil / Kufxy Syp": "MED-0008",
        "Salberry / Berryflow Sachet": "MED-0009",  # primary Salberry; Berry Flow is MED-0010
        "Mediscon Liquid 120ml": "MED-0011",
        "Medivit Syp 120ml": "MED-0012",
        "Paxcal Syp 120ml": "MED-0016",
        "Paxcal Tab 20's": "MED-0017",
        "V-Fol Tab": "MED-0018",
        "Nida 500mg/100ml": "MED-0022",
        "Novagen 1G": "MED-0026",
        "Lancix Inj. 10's": "MED-0027",
        "Lancix Inj. 25's": "MED-0028",
        "G.Tax 1g": "MED-0031",
        "ColiMax Drops": "MED-0034",
        "Ectafin 1G Inj.": "MED-0035",
        "Ectafin 2G Inj.": "MED-0036",
        "Clan Plus Syp 120ml": "MED-0037",
        "Clan Plus Tab": "MED-0037",
        "Trenmed Tab 20's": "MED-0038",
        "Maxy 400mg/250ml": "MED-0039",
        "Zil 20mg Cap": "MED-0041",
        "Zil 40mg Cap": "MED-0042",
        # KhaajGo Bar 85G — no matching SKU in product master (skip)
    }

    def match_sku(product_name: str) -> str | None:
        if product_name in EXPLICIT_OVERRIDES:
            return EXPLICIT_OVERRIDES[product_name]
        if product_name in by_exact:
            return by_exact[product_name]
        nk = norm_key(product_name)
        if nk in by_norm:
            return by_norm[nk]
        for part in re.split(r"[/|]", product_name):
            part = part.strip()
            if not part:
                continue
            if part in by_exact:
                return by_exact[part]
            if norm_key(part) in by_norm:
                return by_norm[norm_key(part)]
        best_sku = None
        best = 0.0
        for p in products:
            a = norm_key(product_name)
            b = norm_key(p["name"])
            score = SequenceMatcher(None, a, b).ratio()
            if score > best:
                best = score
                best_sku = p["sku"]
        if best >= 0.78:
            return best_sku
        return None

    # Build map of all target product names that resolve
    EXPLICIT: dict[str, str] = {}
    target_products = sorted({r["productName"] for r in all_rows})
    unmatched = []
    for tp in target_products:
        sku = match_sku(tp)
        if sku:
            EXPLICIT[tp] = sku
        else:
            unmatched.append(tp)

    print("\n=== Unmatched target products ===")
    for u in unmatched:
        # show best candidate
        best = max(products, key=lambda p: SequenceMatcher(None, norm_key(u), norm_key(p["name"])).ratio())
        score = SequenceMatcher(None, norm_key(u), norm_key(best["name"])).ratio()
        print(f"  MISS {u!r} best={best['name']!r} score={score:.2f}")

    # Geo + managers from target rows
    managers = sorted({r["manager"] for r in all_rows} | {"Vacant"})
    territories = {}
    areas = {}
    regions = {}
    zones = {}

    # Prefer field-force designations for territory ownership
    TERR_DESIG_RANK = {"TM": 0, "STM": 1, "SO": 2, "WS": 3, "ASM": 4, "SASM": 5, "HOS": 6, "Sr. HOS": 7}
    AREA_DESIG_RANK = {"ASM": 0, "SASM": 1, "HOS": 2, "Sr. HOS": 3, "BM": 4, "TM": 5, "SO": 6}
    REGION_DESIG_RANK = {"HOS": 0, "Sr. HOS": 1, "ASM": 2, "BUH": 3, "BUM": 4, "BM": 5}
    ZONE_DESIG_RANK = {"BUH": 0, "BUM": 1, "Sr. HOS": 2, "HOS": 3, "ASM": 4, "PAK1": 5, "PAK2": 6, "National": 7}

    def pick_manager(counter_by_desig_name: dict, rank_map: dict) -> str:
        # counter keys (manager, desig) -> count
        best = None
        best_key = (999, -1, "")
        for (mgr, desig), cnt in counter_by_desig_name.items():
            rank = rank_map.get(desig or "", 50)
            key = (rank, -cnt, mgr)
            if best is None or key < best_key:
                best = mgr
                best_key = key
        return best or "Vacant"

    terr_votes = defaultdict(Counter)
    area_votes = defaultdict(Counter)
    region_votes = defaultdict(Counter)
    zone_votes = defaultdict(Counter)

    for r in all_rows:
        terr_votes[r["territory"]][(r["manager"], r["designation"])] += 1
        area_votes[r["area"]][(r["manager"], r["designation"])] += 1
        region_votes[r["region"]][(r["manager"], r["designation"])] += 1
        zone_votes[r["zone"]][(r["manager"], r["designation"])] += 1

    geo = {
        "managers": managers,
        "territories": [
            {"name": name, "manager": pick_manager(votes, TERR_DESIG_RANK)}
            for name, votes in sorted(terr_votes.items())
        ],
        "areas": [
            {"name": name, "manager": pick_manager(votes, AREA_DESIG_RANK)}
            for name, votes in sorted(area_votes.items())
        ],
        "regions": [
            {"name": name, "manager": pick_manager(votes, REGION_DESIG_RANK)}
            for name, votes in sorted(region_votes.items())
        ],
        "zones": [
            {"name": name, "manager": pick_manager(votes, ZONE_DESIG_RANK)}
            for name, votes in sorted(zone_votes.items())
        ],
    }

    # Product targets: one row per product+geo+month; manager = sheet Name
    targets = []
    skipped_no_product = 0
    for r in all_rows:
        sku = EXPLICIT.get(r["productName"]) or match_sku(r["productName"])
        if not sku:
            skipped_no_product += 1
            continue
        for m in r["months"]:
            targets.append(
                {
                    "sku": sku,
                    "year": m["year"],
                    "month": m["month"],
                    "territory": r["territory"],
                    "area": r["area"],
                    "region": r["region"],
                    "zone": r["zone"],
                    "manager": r["manager"],
                    "quantity": m["quantity"],
                }
            )

    # Dedupe by unique key — sum quantities if duplicates
    merged = {}
    for t in targets:
        key = (t["sku"], t["year"], t["month"], t["territory"], t["area"], t["region"], t["zone"])
        if key in merged:
            merged[key]["quantity"] += t["quantity"]
            # keep first manager
        else:
            merged[key] = dict(t)
    targets = list(merged.values())

    # Also add target product names as aliases on products for future matching
    alias_additions = defaultdict(set)
    for tp, sku in EXPLICIT.items():
        prod = next(p for p in products if p["sku"] == sku)
        if tp != prod["name"]:
            alias_additions[sku].add(tp)
    for p in products:
        extra = sorted(alias_additions.get(p["sku"], []))
        for a in extra:
            if a not in p["aliases"]:
                p["aliases"].append(a)

    write_ts_const(OUT / "products.ts", "SEED_PRODUCTS", products)
    write_ts_const(OUT / "geo.ts", "SEED_GEO", geo)
    write_ts_const(OUT / "product-targets.ts", "SEED_PRODUCT_TARGETS", targets)

    summary = {
        "products": len(products),
        "managers": len(managers),
        "territories": len(geo["territories"]),
        "areas": len(geo["areas"]),
        "regions": len(geo["regions"]),
        "zones": len(geo["zones"]),
        "productTargets": len(targets),
        "skippedTargetRowsNoProduct": skipped_no_product,
        "unmatchedProductNames": unmatched,
    }
    (OUT / "seed-summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("\n=== Summary ===")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
